In [1]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [2]:
# Creating a NumPy Array
lst=[1.5,"string",True]

arr= np.array(lst)
print(arr)

['1.5' 'string' 'True']


In [3]:
# .dtype attribute
print(arr.dtype)

<U32


In [5]:
"""
Size Comparison of ndarray and list objects
"""

from sys import getsizeof

lst = [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17]
print(getsizeof(lst))

arr = np.array(lst)
print(getsizeof(arr))

lst = []
print(getsizeof(lst))
arr = np.array(lst)
print(getsizeof(arr))

192
164
56
96


In [7]:
prices = [30,25,40,20,20,35,50,35]

new_prices = [price-5 for price in prices]
print(new_prices)

prices_arr=np.array(prices)
prices_arr=prices_arr-5
print(prices_arr)

[25, 20, 35, 15, 15, 30, 45, 30]
[25 20 35 15 15 30 45 30]


In [8]:
test1 = np.array([92,94,88,91,87])
test2 = np.array([79,100,86,93,91])
test3 = np.array([87,85,72,90,92])

test3_fixed = test3 +2
print(test3_fixed)

total_grade = test1 + test2 + test3
print(total_grade)

final_grade = total_grade/3
print(final_grade)

jeremy_test2 = test2[3]
print(jeremy_test2)

manual_adwoa_test1 = np.array([test1[1],test1[2]])
print(manual_adwoa_test1)

student_scores = np.array([test1 , test2 , test3])
print(student_scores)

print(student_scores[2,0])
print(student_scores[:,4])

[89 87 74 92 94]
[258 279 246 274 270]
[86.         93.         82.         91.33333333 90.        ]
93
[94 88]
[[ 92  94  88  91  87]
 [ 79 100  86  93  91]
 [ 87  85  72  90  92]]
87
[87 91 92]


In [10]:
a= np.array([10,2,2,4,5,3,9,8,9,7])
mask = a>5
print(mask)

selected = a[a>5]
print(selected)

selected = a[(a>6)|(a<4)]
print(selected)

selected = a[(a>4)&(a<8)]
print(selected)

[ True False False False False False  True  True  True  True]
[10  9  8  9  7]
[10  2  2  3  9  8  9  7]
[5 7]


In [14]:
#실습문제

#포리지 온도를 porridge 배열 저장
porridge = np.array([79,65,50,63,56,90,85,98,79,51])
#60도 미만 cold 배열에 저장
cold=porridge[porridge<60]
#80도 초과 hot 배열에 저장
hot=porridge[porridge>80]
#60도 이상 80도 이하 적당 just_right 배열에 저장
just_right=porridge[(porridge>=60)&(porridge<=80)]

print(porridge)
print(cold)
print(hot)
print(just_right)

[79 65 50 63 56 90 85 98 79 51]
[50 56 51]
[90 85 98]
[79 65 63 79]
